name: Backend Deploy

on:
  push:
    branches:
      - main
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Set environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "ENV_FILE=prod.env" >> $GITHUB_ENV
            echo "DOCKER_COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
            echo "SERVICE_NAME=backend-prod" >> $GITHUB_ENV
          else
            echo "ENV_FILE=qa.env" >> $GITHUB_ENV
            echo "DOCKER_COMPOSE_FILE=docker-compose.qa.yml" >> $GITHUB_ENV
            echo "SERVICE_NAME=backend-qa" >> $GITHUB_ENV
          fi

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/mmagna/qr-system
            git pull
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down ${{ env.SERVICE_NAME }}
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} build --no-cache ${{ env.SERVICE_NAME }}
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d ${{ env.SERVICE_NAME }}

      - name: Check deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/mmagna/qr-system
            docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} logs --tail=100 ${{ env.SERVICE_NAME }}