name: Backend Deploy

on:
  push:
    branches:
      - main
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Set environment
        run: |
          if [[ ${{ github.ref_name }} == "main" ]]; then
            echo "ENV_FILE=.env.prod" >> $GITHUB_ENV
          else
            echo "ENV_FILE=.env.qa" >> $GITHUB_ENV
          fi

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/mmagna/qr-system/backend
            git pull
            npm install --production
            pm2 restart app || pm2 start src/main.ts --name "qr-backend"
